[project]
name = "backend"
version = "0.1.0"
description = "Backend server for cover letter ai"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.117.1",
    "python-dotenv>=1.1.1",
]
