from io import BytesIO
from datetime import datetime
from textwrap import wrap
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from docx import Document
# from app.core.logging import logger
import logging

logger = logging.getLogger(__name__)

# Try to use a serif font; fallback to built-in if unavailable
try:
    pdfmetrics.registerFont(TTFont('TimesNewRoman', 'times.ttf'))
    FONT_NAME = 'TimesNewRoman'
except:
    FONT_NAME = 'Times-Roman'


def generate_pdf(
    content: str,
    title: str = "Cover Letter",
    sender_name: str = "Uyonoh M. Turaki",
    sender_email: str = "uyonoh@example.com",
    recipient_name: str = "Hiring Manager",
    recipient_company: str = "Company Name",
    recipient_address: str = "123 Business Road, City, Country",
    include_header: bool = True,
) -> BytesIO:
    """
    Generate a professional PDF cover letter with recipient and signature.
    """

    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Layout and typography
    left_margin = inch
    right_margin = inch
    top_margin = height - inch
    bottom_margin = inch
    line_height = 16
    font_size = 12

    # Base font
    p.setFont(FONT_NAME, font_size)

    # --- Optional Header ---
    if include_header and title:
        p.setFont(FONT_NAME, 18)
        p.drawCentredString(width / 2, top_margin + 20, title)
        p.setFont(FONT_NAME, font_size)

    y = top_margin - 20

    # # --- Sender info ---
    # p.setFont(FONT_NAME, 11)
    # p.setFillGray(0.4)
    # p.drawString(left_margin, y, sender_name)
    # y -= 14
    # p.drawString(left_margin, y, sender_email)
    # p.setFillGray(0)
    # y -= 30


    # --- Recipient info ---
    p.setFont(FONT_NAME, 12)
    p.drawString(left_margin, y, recipient_name)
    y -= 16
    p.drawString(left_margin, y, recipient_company)
    y -= 16
    for line in wrap(recipient_address, width=70):
        p.drawString(left_margin, y, line)
        y -= 16
    # y -= 4

    # --- Date ---
    today = datetime.now().strftime("%B %d, %Y")
    p.drawString(left_margin, y, today)
    y -= 35

    # --- Body content ---
    lines = []
    for raw_line in content.splitlines():
        wrapped = wrap(raw_line, width=95)
        lines.extend(wrapped or [""])

    for line in lines:
        if y < bottom_margin + 80:  # leave space for signature
            p.showPage()
            p.setFont(FONT_NAME, font_size)
            y = top_margin
        p.drawString(left_margin, y, line)
        y -= line_height

    # --- Signature section ---
    if sender_name and sender_email:
        y -= 40
        p.drawString(left_margin, y, "Sincerely,")
        y -= 40
        p.setFont(FONT_NAME, 12)
        p.drawString(left_margin, y, sender_name)
        y -= 16
        p.setFont(FONT_NAME, 10)
        p.setFillGray(0.5)
        p.drawString(left_margin, y, sender_email)
        p.setFillGray(0)

    # # --- Footer ---
    # p.setFont(FONT_NAME, 9)
    # p.setFillGray(0.6)
    # p.drawCentredString(width / 2, bottom_margin - 20, "Generated by CoverLetter.AI")
    # p.setFillGray(0)

    # Finalize
    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer

def generate_docx(content: str, title: str = "Cover Letter") -> BytesIO:
    buffer = BytesIO()
    doc = Document()
    doc.add_heading(title, level=1)
    for line in content.splitlines():
        doc.add_paragraph(line)
    doc.save(buffer)
    buffer.seek(0)
    return buffer